package com.example.unserhoersaal.enums;

/** TODO. */
public enum ErrorTag {
  NULL,
  EMAIL,
  USERNAME,
  CURRENT_PASSWORD,
  NEW_PASSWORD,
  TITLE,
  TEXT,
  DESCRIPTION,
  INSTITUTION,
  REPO,
  VM,
  TIME_PICKER_DATE,
  TIME_PICKER_TIME,
  TIME_PICKER_HOUR_DURATION,
  TIME_PICKER_MINUTE_DURATION,
  OPTION
}
