package com.example.unserhoersaal.enums;

public enum LoginErrorMessEnum {
  NONE,
  EMAIL_EMPTY,
  PASSWORD_EMPTY,
  EMAIL_WRONG_PATTERN,
  PASSWORD_WRONG_PATTERN,
  EMAIL_AND_PASSWORD_PATTERN_WRONG,
  EMAIL_AND_PASSWORD_EMPTY,
  EMAIL_EMPTY_AND_PASSWORD_PATTERN_WRONG,
  EMAIL_PATTERN_WRONG_AND_PASSWORD_EMPTY,
  WRONG_LOGIN_INPUT
}