package com.example.unserhoersaal.enums;

public enum RegistrationErrorMessEnum {
  NONE,
  EMAIL_EMPTY,
  PASSWORD_EMPTY,
  USER_NAME_EMPTY,
  EMAIL_WRONG_PATTERN,
  PASSWORD_WRONG_PATTERN,
  USER_NAME_WRONG_PATTERN,
  EMAIL_AND_PASSWORD_PATTERN_WRONG,
  EMAIL_PASSWORD_USERNAME_PATTERN_WRONG,
  EMAIL_AND_PASSWORD_EMPTY,
  EMAIL_PASSWORD_USERNAME_EMPTY,
  EMAIL_EMPTY_AND_PASSWORD_PATTERN_WRONG,
  EMAIL_EMPTY_AND_USERNAME_PATTERN_WRONG,
  PASSWORD_EMPTY_AND_EMAIL_PATTERN_WRONG,
  PASSWORD_EMPTY_AND_USERNAME_PATTERN_WRONG,
  USERNAME_EMPTY_AND_EMAIL_PATTERN_WRONG,
  USERNAME_EMPTY_AND_PASSWORD_PATTERN_WRONG,
  REGISTRATION_PROCESS_FAIL
}
