#build release: https://developer.android.com/studio/build/building-cmdline#sign_cmdline
name: Build Debug APK

on:
  push:
    branches: [main]

jobs:

  Build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run Build APK
        run: "./gradlew assembleDebug"

      - name: Save APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app

  Release:
    name: Release Debug APK
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: debug-apk
          path: app

      - name: Release Debug APK
        uses: ShaunLWM/action-release-debugapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_BRANCH: main
          APP_FOLDER: app
          RELEASE_TITLE: debug-apk
