name: Tests

on:
  pull_request:
    branches: [dev, master]

jobs:

  Linting:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew assembleDebug --stacktrace --warning-mode all

      - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v1
        with:
          xml_path: build/reports/*.xml

  Tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: Linting

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run Tests
        run: ./gradlew test --stacktrace --warning-mode all

      - name: Report Test Results
        uses: asadmansr/android-test-report-action@v1.2.0

  Checksytyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest
    needs: Tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
