name: Tests

on:
  push:
    branches: [dev]

jobs:

  Tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Run Tests
        run: "./gradlew test"

      - name: Report Test Results
        uses: asadmansr/android-test-report-action@v1.2.0

  Linting:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          lint_xml_file: app/build/lint-reports/lint-results.xml


